[package]
name = "locolized-errors"
version = "0.1.0"
edition = "2024"
description="Better loco.rs i18n errors"
license="MIT"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
locolized-errors-macros={path="../locolized-errors-macros"}
loco-rs = { version = "0.16" }
axum = "0.8"
